"""The simulated institutions Epilogue corresponds with.

Every institution here is fictional (the Social Security Administration is
modeled generically as "the federal benefits agency" under a simulated
stand-in). Each has a small state machine that mirrors how such organizations
really behave after a death notification: they demand certified documents,
take days to answer, sometimes never answer at all, occasionally bill the
dead, and — in the case of credit bureaus — quietly catch identity thieves
trying to open accounts in a dead person's name.

Replies are not generated by an LLM. They are deterministic scripts, which
keeps the *world* honest while the *agent* stays fully model-driven — the
same discipline you'd use to evaluate any autonomous system.
"""

from __future__ import annotations

import json
import threading
from dataclasses import dataclass, field
from datetime import date, timedelta

from ..domain import MailMessage
from ..ledger import Ledger


@dataclass
class Institution:
    id: str
    name: str
    kind: str  # matches DiscoveredAccount.institution_kind / playbook kinds
    script: str  # behavior key
    contact: str = "secure message portal"
    notes: str = ""


INSTITUTIONS: dict[str, Institution] = {
    i.id: i
    for i in [
        Institution(
            "first_harbor_bank",
            "First Harbor Bank",
            "bank",
            "bank",
            notes="Checking ...4417 and savings ...9052",
        ),
        Institution(
            "meridian_card", "Meridian Card Services", "credit_card", "credit_card", notes="Visa ending 7734"
        ),
        Institution(
            "fed_benefits",
            "Federal Benefits Agency (SSA)",
            "government",
            "ssa",
            notes="Retirement benefits, direct deposit",
        ),
        Institution(
            "ohio_light_power",
            "Ohio Light & Power",
            "utility",
            "utility",
            notes="Service at 44 Maple Crest Dr",
        ),
        Institution(
            "streamflix", "StreamFlix", "subscription", "streamflix", notes="Family streaming plan, $15.99/mo"
        ),
        Institution(
            "pixelvault",
            "PixelVault Cloud Photos",
            "digital",
            "pixelvault",
            notes="2TB photo plan, renews annually",
        ),
        Institution(
            "ironworks_gym", "IronWorks Fitness", "gym", "gym", notes="Month-to-month membership, $42/mo"
        ),
        Institution(
            "beacon_mutual",
            "Beacon Mutual Life",
            "insurance",
            "insurance",
            notes="Term life policy BML-88213",
        ),
        Institution("equifax_sim", "Equifax (simulated)", "credit_bureau", "bureau"),
        Institution("experian_sim", "Experian (simulated)", "credit_bureau", "bureau_watch"),
        Institution("transunion_sim", "TransUnion (simulated)", "credit_bureau", "bureau"),
        Institution(
            "skyway_airlines", "Skyway Airlines", "airline", "airline", notes="SkyMiles balance 84,210"
        ),
        Institution(
            "clearline_wireless", "ClearLine Wireless", "telecom", "telecom", notes="One line, $38/mo"
        ),
        Institution(
            "daily_ledger_news",
            "The Daily Ledger",
            "subscription",
            "newspaper",
            notes="Annual print+digital, prepaid through March",
        ),
        Institution("ohio_unclaimed", "Ohio Division of Unclaimed Funds", "government", "unclaimed"),
    ]
}


def _has_death_cert(attachments: list[str]) -> bool:
    joined = " ".join(attachments).lower()
    return "death" in joined and "cert" in joined


def _has_certified_cert(attachments: list[str]) -> bool:
    """Institutions that demand a CERTIFIED death certificate mean it — a
    photocopy comes back with a reminder, which is exactly what makes the
    finite certified copies in the vault a real constraint."""
    joined = " ".join(attachments).lower()
    return "certified" in joined and "death" in joined and "cert" in joined


def _is_written_letter(channel: str) -> bool:
    return channel in ("letter", "mailed_letter")


@dataclass
class _Reply:
    delay_days: int
    subject: str
    body: str
    next_stage: str
    silent: bool = False  # institution does not respond at all


@dataclass
class ScheduledDelivery:
    due: str  # ISO date
    institution_id: str
    subject: str
    body: str
    task_id: str | None = None
    skip_if_stage: str | None = None  # skip when the stage key already equals this
    stage_key: str | None = None
    extra: dict = field(default_factory=dict)


class SimWorld:
    """Deterministic behavior engine + scheduled delivery queue."""

    _queue_lock = threading.Lock()  # guards the shared delivery queue's read-modify-write

    def __init__(self, ledger: Ledger) -> None:
        self.ledger = ledger

    # -- stage bookkeeping -------------------------------------------------

    def _stage_key(self, institution_id: str, task_id: str | None) -> str:
        return f"sim:stage:{institution_id}:{task_id or 'general'}"

    def get_stage(self, institution_id: str, task_id: str | None) -> str:
        return self.ledger.kv_get(self._stage_key(institution_id, task_id), "new") or "new"

    def set_stage(self, institution_id: str, task_id: str | None, stage: str) -> None:
        self.ledger.kv_set(self._stage_key(institution_id, task_id), stage)
        # Also track the institution's latest stage regardless of task, so scheduled
        # world events (like renewal reminders) can be suppressed once a matter is settled.
        self.ledger.kv_set(f"sim:inststage:{institution_id}", stage)

    # -- delivery queue ----------------------------------------------------

    def _queue(self) -> list[dict]:
        raw = self.ledger.kv_get("sim:queue", "[]") or "[]"
        return json.loads(raw)

    def _save_queue(self, queue: list[dict]) -> None:
        self.ledger.kv_set("sim:queue", json.dumps(queue))

    def schedule(self, case_id: str, delivery: ScheduledDelivery) -> None:
        with self._queue_lock:
            queue = self._queue()
            queue.append({"case_id": case_id, **delivery.__dict__})
            self._save_queue(queue)

    def deliver_due(self, case_id: str) -> list[MailMessage]:
        """Move every due scheduled reply into the case inbox. Called by the Vigil each cycle."""
        with self._queue_lock:
            return self._deliver_due_locked(case_id)

    def _deliver_due_locked(self, case_id: str) -> list[MailMessage]:
        today = self.ledger.sim_today()
        queue = self._queue()
        keep, delivered = [], []
        for item in queue:
            if item.get("case_id") != case_id or date.fromisoformat(item["due"]) > today:
                keep.append(item)
                continue
            if item.get("skip_if_stage") and item.get("stage_key"):
                if (self.ledger.kv_get(item["stage_key"], "new") or "new") == item["skip_if_stage"]:
                    continue  # event no longer applies (e.g. renewal already handled)
            inst = INSTITUTIONS[item["institution_id"]]
            subject, body = item["subject"], item["body"]
            if (item.get("extra") or {}).get("event") == "fraud_attempt":
                # The outcome genuinely depends on what the agent did: only a placed
                # deceased alert (any bureau brought to stage "done") stops the thief.
                subject, body = self._fraud_attempt_outcome()
            mail = MailMessage(
                case_id=case_id,
                direction="inbound",
                institution_id=inst.id,
                institution_name=inst.name,
                subject=subject,
                body=body,
                task_id=item.get("task_id"),
                sim_date=today,
            )
            self.ledger.save_mail(mail)
            self.ledger.record(
                case_id,
                actor="Postal service",
                kind="mail_received",
                summary=f"Reply arrived from {inst.name}: “{subject}”",
                detail=body,
                task_id=item.get("task_id"),
            )
            delivered.append(mail)
        self._save_queue(keep)
        return delivered

    # -- submission --------------------------------------------------------

    def submit(
        self,
        case_id: str,
        task_id: str | None,
        institution_id: str,
        channel: str,
        subject: str,
        body: str,
        attachments: list[str],
        payment_amount_usd: float = 0,
    ) -> str:
        """Epilogue sends something to an institution. Returns a human-readable receipt."""
        inst = INSTITUTIONS.get(institution_id)
        if inst is None:
            known = ", ".join(sorted(INSTITUTIONS))
            return f"ERROR: unknown institution '{institution_id}'. Known institutions: {known}"

        today = self.ledger.sim_today()
        outbound = MailMessage(
            case_id=case_id,
            direction="outbound",
            institution_id=inst.id,
            institution_name=inst.name,
            channel=channel,
            subject=subject,
            body=body,
            task_id=task_id,
            status="sent",
            sim_date=today,
        )
        self.ledger.save_mail(outbound)

        stage = self.get_stage(inst.id, task_id)
        reply = self._respond(inst, stage, channel, body, attachments, payment_amount_usd)
        if reply is None:
            return f"Delivered to {inst.name} via {channel}. No immediate acknowledgment."
        self.set_stage(inst.id, task_id, reply.next_stage)
        if reply.silent:
            return (
                f"Delivered to {inst.name} via {channel}. The portal accepted the request "
                f"but issued no confirmation number."
            )
        self.schedule(
            case_id,
            ScheduledDelivery(
                due=(today + timedelta(days=reply.delay_days)).isoformat(),
                institution_id=inst.id,
                subject=reply.subject,
                body=reply.body,
                task_id=task_id,
            ),
        )
        return (
            f"Delivered to {inst.name} via {channel}. They typically respond within "
            f"{reply.delay_days} day(s)."
        )

    # -- behavior scripts --------------------------------------------------

    def _respond(
        self, inst: Institution, stage: str, channel: str, body: str, attachments: list[str],
        payment_amount_usd: float = 0,
    ) -> _Reply | None:
        handler = getattr(self, f"_script_{inst.script}")
        if inst.script in ("ssa", "telecom"):
            return handler(inst, stage, channel, body, attachments, payment_amount_usd)
        return handler(inst, stage, channel, body, attachments)

    def _script_bank(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if _has_death_cert(attachments) and not _has_certified_cert(attachments):
            return _Reply(
                3,
                "Photocopies are not accepted",
                "Thank you for the documentation. However, a photocopy of the death certificate "
                "cannot be accepted for estate actions; we require a CERTIFIED copy issued by the "
                "vital records office, together with a signed letter of instruction.\n\n— Estate "
                f"Services, {inst.name}",
                "awaiting_docs",
            )
        if stage == "new" and not _has_certified_cert(attachments):
            return _Reply(
                3,
                "Additional documentation required",
                f"Dear Personal Representative,\n\nWe are sorry for your loss. Before {inst.name} can "
                "restrict the accounts of the late account holder, we require:\n"
                "  1. A certified copy of the death certificate (photocopies are not accepted)\n"
                "  2. A letter of instruction signed by the executor\n\n"
                "Please submit both through our estate services portal.\n\n— Estate Services, "
                f"{inst.name}",
                "awaiting_docs",
            )
        if stage in ("new", "awaiting_docs") and _has_certified_cert(attachments):
            return _Reply(
                4,
                "Accounts restricted — date-of-death balance letter enclosed",
                "Dear Personal Representative,\n\nThe documentation has been verified. Both accounts are "
                "now restricted against new activity. Enclosed is the date-of-death balance letter:\n"
                "  • Checking ...4417 — $4,218.55\n  • Savings ...9052 — $27,840.12\n\n"
                "Scheduled utility autopayments will continue for 60 days to protect the household, per "
                "your instruction. No safe-deposit box is associated with these accounts.\n\n— Estate "
                f"Services, {inst.name}",
                "done",
            )
        if stage in ("new", "awaiting_docs"):
            return _Reply(
                3,
                "Reminder: documentation still required",
                "We still require a certified death certificate and a signed letter of instruction to "
                "proceed.\n\n— Estate Services",
                stage if stage != "new" else "awaiting_docs",
            )
        return None

    def _script_credit_card(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new" and _has_death_cert(attachments):
            return _Reply(
                3,
                "Account closed; interest frozen as of date of death",
                "The account ending 7734 has been closed. Interest and fees are waived from the date of "
                "death. Final balance: $312.09, payable by the estate. Recurring merchants on file: "
                "StreamFlix, IronWorks Fitness, ClearLine Wireless.\n\n— Estate Resolution Team",
                "done",
            )
        if stage == "new":
            return _Reply(
                2,
                "We need a copy of the death certificate",
                "To close this account we require a copy of the death certificate (a photocopy is "
                "acceptable). Interest is paused for 30 days pending receipt.\n\n— Estate Resolution Team",
                "awaiting_docs",
            )
        if stage == "awaiting_docs" and _has_death_cert(attachments):
            return self._script_credit_card(inst, "new", channel, body, ["death certificate copy"])
        return None

    def _script_ssa(self, inst, stage, channel, body, attachments, payment_amount_usd=0) -> _Reply | None:
        if stage == "new":
            return _Reply(
                7,
                "Death recorded — action required regarding final benefit payment",
                "The death has been recorded against the beneficiary's record and monthly retirement "
                "benefits have stopped.\n\nIMPORTANT: A benefit payment of $1,847.00 was deposited on "
                "September 3 for the month of death. Benefits are not payable for the month of death, and "
                "this amount must be returned. Please arrange repayment from the receiving account.\n\n"
                "Our screening shows no surviving spouse on record; the lump-sum death payment does not "
                "apply. Dependent survivor benefits: none identified.\n\n— Survivor Services",
                "await_repayment",
            )
        if stage == "await_repayment":
            if payment_amount_usd == 1847:
                return _Reply(
                    5,
                    "Repayment received — record closed",
                    "The returned benefit payment of $1,847.00 has been received and the record is now "
                    "closed. No further action is required. We are sorry for your loss.\n\n— Survivor "
                    "Services",
                    "done",
                )
            return _Reply(
                5,
                "Reminder: benefit payment must still be returned",
                "Our records show the $1,847.00 benefit payment for the month of death has not yet "
                "been returned. Please arrange repayment from the receiving account.\n\n— Survivor "
                "Services",
                "await_repayment",
            )
        return None

    def _script_utility(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new":
            return _Reply(
                2,
                "How would you like to handle service at 44 Maple Crest Dr?",
                "We've noted the account holder's passing. Please choose one:\n"
                "  (a) TRANSFER the account to the estate or a family member (service continues)\n"
                "  (b) CLOSE the account (service disconnects in 10 days)\n\n"
                "Note: the home appears to be unoccupied. If it will be sold, most families keep power on "
                "to protect the property.\n\n— Customer Care, Ohio Light & Power",
                "awaiting_choice",
            )
        if stage == "awaiting_choice":
            lowered = body.lower()
            if "transfer" in lowered:
                return _Reply(
                    3,
                    "Account transferred to the estate",
                    "The account is now billed to the Estate of the late account holder, care of the "
                    "executor. Service continues uninterrupted. Final balance under the previous name: "
                    "$0.00.\n\n— Customer Care",
                    "done",
                )
            if "close" in lowered:
                return _Reply(
                    3,
                    "Closure scheduled",
                    "Service will disconnect in 10 days. A final bill will follow.\n\n— Customer Care",
                    "done",
                )
        return None

    def _script_streamflix(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new":
            return _Reply(
                2,
                "Before we close this account…",
                "We can cancel the subscription effective today. One thing first: this account has two "
                "family member profiles with years of watch history and saved lists (including "
                "'Dad's Westerns' — 214 titles). We can transfer the profiles to another member's account "
                "before closing, or close now and delete them permanently. Which would you like?\n\n"
                "— StreamFlix Support",
                "awaiting_choice",
            )
        if stage == "awaiting_choice":
            lowered = body.lower()
            if "transfer" in lowered or "preserve" in lowered or "keep" in lowered:
                return _Reply(
                    2,
                    "Profiles transferred — subscription cancelled",
                    "Both profiles, including all saved lists and history, have been transferred to the "
                    "family account you designated. Billing has stopped. No further charges will occur.\n\n"
                    "— StreamFlix Support",
                    "done",
                )
            return _Reply(
                2,
                "Subscription cancelled",
                "The account has been closed and billing stopped.\n\n— StreamFlix Support",
                "done",
            )
        return None

    def _script_pixelvault(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new":
            lowered = body.lower()
            if "export" in lowered or "archive" in lowered or "download" in lowered:
                return _Reply(
                    3,
                    "Your archive is ready — 22,384 photos",
                    "The full-resolution archive of this library (22,384 photos and 511 videos, 1.9 TB) is "
                    "ready for download. The link is valid for 30 days. Once you confirm the download, "
                    "the paid plan can be downgraded so no renewal will occur, while the library remains "
                    "viewable read-only.\n\n— PixelVault",
                    "archive_ready",
                )
            return _Reply(
                2,
                "Account holder deceased — plan options",
                "We can (a) provide a full archive export before any change, (b) downgrade the plan to "
                "read-only, or (c) delete the library. Deletion is permanent and cannot be undone. "
                "Please confirm the family's wishes.\n\n— PixelVault",
                "awaiting_choice",
            )
        if stage in ("awaiting_choice", "archive_ready"):
            return _Reply(
                2,
                "Done — no renewal will occur",
                "The plan has been downgraded to free read-only storage. The upcoming annual renewal of "
                "$119.88 has been cancelled. The library remains safe and viewable.\n\n— PixelVault",
                "done",
            )
        return None

    def _script_gym(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new" and not _is_written_letter(channel):
            # The classic gym move: the online cancellation goes into a void.
            return _Reply(0, "", "", "portal_void", silent=True)
        if _is_written_letter(channel):
            return _Reply(
                3,
                "Membership cancelled — post-date charge refunded",
                "Per section 9(c) of the membership agreement, written notice has been accepted. The "
                "membership is cancelled. Our records show a $42.00 dues charge processed after the date "
                "of death; a refund has been issued to the card on file. We're sorry for your loss.\n\n"
                "— Member Services, IronWorks Fitness",
                "done",
            )
        if stage == "portal_void":
            return _Reply(
                2,
                "Regarding your cancellation request",
                "Per the membership agreement, cancellations must be submitted as WRITTEN NOTICE by mail. "
                "Portal and phone requests cannot be processed.\n\n— Member Services, IronWorks Fitness",
                "told_letter_required",
            )
        return None

    def _script_insurance(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new":
            return _Reply(
                4,
                "Claim opened — beneficiary signature required",
                "Claim BML-88213-C has been opened. Enclosed is the claim packet, pre-filled from your "
                "notice. To disburse, we require:\n  1. The beneficiary's signature on form LC-2 (wet "
                "ink)\n  2. A certified copy of the death certificate\n\nOnce received, payment is issued "
                "within 7 business days.\n\n— Claims, Beacon Mutual Life",
                "awaiting_signature",
            )
        if stage == "awaiting_signature" and _has_death_cert(attachments) and not _has_certified_cert(attachments):
            return _Reply(
                3,
                "Certified copy required to disburse",
                "We received the signed form. Disbursement additionally requires a CERTIFIED copy of "
                "the death certificate; a photocopy cannot be accepted for a claim of this size.\n\n"
                "— Claims, Beacon Mutual Life",
                "awaiting_signature",
            )
        if stage == "awaiting_signature" and _has_certified_cert(attachments):
            return _Reply(
                7,
                "Claim approved — benefit disbursed",
                "The claim has been approved. The policy benefit of $150,000.00 has been disbursed to the "
                "named beneficiary by check. Interest of $214.16 accrued during processing is included, "
                "as required by state law.\n\n— Claims, Beacon Mutual Life",
                "done",
            )
        return None

    def _script_bureau(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new":
            return _Reply(
                3,
                "Deceased alert placed on credit file",
                "A deceased — do not issue credit alert is now on the file. New applications will be "
                "automatically declined. A copy of the current credit report is enclosed for the estate; "
                "it lists 4 open tradelines, consistent with the accounts already known to you.\n\n— "
                f"Consumer Assistance, {inst.name}",
                "done",
            )
        return None

    def _script_bureau_watch(self, inst, stage, channel, body, attachments) -> _Reply | None:
        # Same as bureau, but this one will also be the source of the fraud-attempt event.
        return self._script_bureau(inst, stage, channel, body, attachments)

    def _script_airline(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new" and _has_death_cert(attachments):
            return _Reply(
                5,
                "SkyMiles transferred under bereavement policy",
                "Under our bereavement policy, the balance of 84,210 miles has been transferred to the "
                "family member named in your request, with the transfer fee waived. The account is now "
                "closed.\n\n— SkyMiles Service Center",
                "done",
            )
        if stage == "new":
            return _Reply(
                3,
                "Bereavement transfer — documentation needed",
                "Mileage balances are transferable to immediate family upon request with a copy of the "
                "death certificate. Please attach it and the recipient's name.\n\n— SkyMiles Service "
                "Center",
                "awaiting_docs",
            )
        if stage == "awaiting_docs" and _has_death_cert(attachments):
            return self._script_airline(inst, "new", channel, body, ["death certificate copy"])
        return None

    def _script_telecom(self, inst, stage, channel, body, attachments, payment_amount_usd=0) -> _Reply | None:
        if stage == "new":
            return _Reply(
                3,
                "Line cancelled — final bill",
                "The line has been disconnected with the early-termination fee waived under our "
                "bereavement policy. Final prorated bill: $19.20, payable by the estate. The number will "
                "be held for 90 days should the family wish to port it.\n\n— ClearLine Wireless",
                "awaiting_payment",
            )
        if stage in ("awaiting_payment", "done"):
            if payment_amount_usd == 19.20:
                return _Reply(2, "Final payment received — zero balance",
                              "The estate's final payment of $19.20 has been received. The line is closed "
                              "and no further balance is due.\n\n— ClearLine Wireless", "paid")
            return _Reply(2, "Final bill remains outstanding",
                          "The line is closed. No payment has been received; the estate's final balance "
                          "remains $19.20. Please remit the final payment.\n\n— ClearLine Wireless", "awaiting_payment")
        return None

    def _script_newspaper(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new":
            return _Reply(
                2,
                "Subscription cancelled — prorated refund issued",
                "The subscription has been cancelled. A prorated refund of $61.40 for the unused portion "
                "of the annual term has been issued by check to the estate.\n\n— The Daily Ledger",
                "done",
            )
        return None

    def _script_unclaimed(self, inst, stage, channel, body, attachments) -> _Reply | None:
        if stage == "new":
            return _Reply(
                5,
                "Claim verified — funds released to the estate",
                "The claim against the unclaimed funds record has been verified: a forgotten utility "
                "deposit of $312.00 held under the decedent's former address. The funds have been "
                "released to the estate by check.\n\n— Division of Unclaimed Funds",
                "done",
            )
        return None

    # -- scripted world events --------------------------------------------

    def _fraud_attempt_outcome(self) -> tuple[str, str]:
        """The identity thief strikes on day 9 either way. Whether they succeed
        depends entirely on whether the agent got deceased alerts placed in time —
        the world checks, so the demo's protection moment is earned, not scripted."""
        alert_placed = any(
            self.ledger.kv_get(f"sim:inststage:{b}") == "done"
            for b in ("equifax_sim", "experian_sim", "transunion_sim")
        )
        if alert_placed:
            return (
                "ALERT: credit application blocked on protected file",
                "An application for a retail credit card was received today naming the deceased as "
                "applicant (address in another state). Because a deceased alert is present on this "
                "file, the application was AUTOMATICALLY DECLINED and flagged for fraud review. No "
                "action is required, but the estate may wish to retain this notice.\n\n— Fraud "
                "Operations, Experian (simulated)",
            )
        return (
            "New account opened — welcome letter returned to sender",
            "A retail credit card application in the deceased's name was APPROVED this week (no "
            "deceased indicator was present on the file at the time). The welcome letter was "
            "returned undeliverable, which triggered this review. The account shows $1,240 in "
            "charges. Please contact our fraud department to begin an affidavit — resolution "
            "typically takes 30-60 days.\n\n— Fraud Operations, Experian (simulated)",
        )

    def seed_case_events(self, case_id: str) -> None:
        """Ambient events that happen TO the estate, independent of Epilogue's actions."""
        today = self.ledger.sim_today()
        # Day +9: an identity thief tries to open a card in the deceased's name.
        # The outcome is decided at delivery time by _fraud_attempt_outcome().
        self.schedule(
            case_id,
            ScheduledDelivery(
                due=(today + timedelta(days=9)).isoformat(),
                institution_id="experian_sim",
                subject="",
                body="",
                extra={"event": "fraud_attempt"},
            ),
        )
        # Day +8: PixelVault renewal reminder, IF the matter hasn't been settled by then.
        self.schedule(
            case_id,
            ScheduledDelivery(
                due=(today + timedelta(days=8)).isoformat(),
                institution_id="pixelvault",
                subject="Your annual plan renews in 4 days",
                body=(
                    "A reminder that the 2TB plan on this account renews on the 12th for $119.88, charged "
                    "to the Visa ending 7734.\n\n— PixelVault"
                ),
                skip_if_stage="done",
                stage_key="sim:inststage:pixelvault",
            ),
        )
